version: "3"

services:
 osclass:
  build: ./osclass
  env_file:
    - ./common.env
  ports:
    - "80:80"
  volumes:
    - /opt/osclass/html:/var/www/html
    - /backup:/backup
  networks:
    - osclassnetwork

 postfix:
  build: ./postfix
  env_file:
    - ./common.env
  ports:
    - "25:25"

 mysql:
  image: mysql:5.6
  env_file:
    - ./common.env
  expose:
    - "3306"
  networks:
    - osclassnetwork
  volumes:
    - "./mysql/conf.d:/etc/mysql/conf.d"
    - /opt/osclass/data:/var/lib/mysql

networks:
  osclassnetwork:
